apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki-deploy
spec:
  selector:
    matchLabels:
      run: mediawiki
  replicas: 2
  template:
    metadata:
      labels:
        run: mediawiki
    spec:
      containers:
      - name: mediawiki01
        image: docker.io/arunpmohanandocker/learn01:mediawiki
        ports:
        - containerPort: 8080
          name: http-web-svc
          
      