apiVersion: v1
kind: Service
type:
metadata:
  labels:
    name: mariadb
  name: mariadb
spec:
  ports:
  - name: "3306"
    port: 3306    
  type : NodePort  
  selector:
    run : mariadb
---
apiVersion: v1
kind: Service
type:
metadata:
  labels:
    name: mediawiki
  name: mediawiki
spec:
  ports:
  - name: "8080"
    port: 8080
  type : NodePort  
  selector:
    run : mediawiki
   